# Generated by Django 4.1 on 2022-11-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.TextField()),
                ('car_number', models.TextField()),
                ('is_cheking', models.IntegerField(default=1)),
                ('is_registered', models.IntegerField(default=0)),
                ('sts', models.ImageField(blank=True, null=True, upload_to='sts')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('Ж', 'Женский')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('list_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.electrocar')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
